package einvoice

var TypeDocument = map[string]string{
	"TD01": "Fattura",
	"TD04": "Nota di credito",
	"TD05": "Nota di debito",
	"TD07": "Fattura semplificata",
	"TD08": "Nota di Credito semplificata",
	"TD10": "Fattura per acquisto intracomunitario beni",
	"TD11": "Fattura per acquisto intracomunitario servizi",
	"TD12": "Documento riepilogativo (art.6,DPR 695/1996)",
}

var NatureWithDescription = map[string]string{
	"N1":   "escluse ex art.15",
	"N2":   "non soggette",
	"N2.1": "non soggette ad IVA ai sensi degli artt. Da 7 a 7-septies del DPR 633/72",
	"N2.2": "non soggette – altri casi",
	"N3":   "non imponibili",
	"N3.1": "non imponibili – esportazioni",
	"N3.2": "non imponibili – cessioni intracomunitarie",
	"N3.3": "non imponibili – cessioni verso San Marino",
	"N3.4": "non imponibili – operazioni assimilate alle cessioni all’esportazione",
	"N3.5": "non imponibili – a seguito di dichiarazioni d’intento",
	"N3.6": "non imponibili – altre operazioni che non concorrono alla formazione del plafond",
	"N4":   "esenti",
	"N5":   "regime del margine / IVA non esposta in fattura",
	"N6":   "inversione contabile (per le operazioni in reverse charge ovvero nei casi di autofatturazione per acquisti extra UE di servizi ovvero per importazioni di beni nei soli casi previsti)",
	"N6.1": "inversione contabile – cessione di rottami e altri materiali di recupero",
	"N6.2": "inversione contabile – cessione di oro e argento puro",
	"N6.3": "inversione contabile – subappalto nel settore edile",
	"N6.4": "inversione contabile – cessione di fabbricati",
	"N6.5": "inversione contabile – cessione di telefoni cellulari",
	"N6.6": "inversione contabile – cessione di prodotti elettronici",
	"N6.7": "inversione contabile – prestazioni comparto edile e settori connessi",
	"N6.8": "inversione contabile – operazioni settore energetico",
	"N6.9": "inversione contabile – altri casi",
	"N7":   "IVA assolta in altro stato UE (vendite a distanza ex art. 40 commi 3 e 4 e art. 41 comma 1 lett. b, DL 331/93; prestazione di servizi di telecomunicazioni, tele-radiodiffusione ed elettronici ex art. 7-sexies lett. f, g, DPR 633/72 e art. 74-sexies, DPR 633/72)",
}

var MethodsPayments = map[string]string{

	"MP01": "contanti",
	"MP02": "assegno",
	"MP03": "assegno circolare",
	"MP04": "contanti presso Tesoreria",
	"MP05": "bonifico",
	"MP06": "vaglia cambiario",
	"MP07": "bollettino bancario",
	"MP08": "carta di pagamento",
	"MP09": "RID",
	"MP10": "RID utenze",
	"MP11": "RID veloce",
	"MP12": "Riba",
	"MP13": "MAV",
	"MP14": "quietanza erario stato",
	"MP15": "giroconto su conti di contabilità speciale",
	"MP16": "domiciliazione bancaria",
	"MP17": "domiciliazione postale",
	"MP18": "bollettino di c/c postale",
	"MP19": "SEPA Direct Debit",
	"MP20": "SEPA Direct Debit CORE",
	"MP21": "SEPA Direct Debit B2B",
	"MP22": "Trattenuta su somme già riscosse",
	"MP23": "PagoPA",
}
